export const FOOTBALL = {
    "ro": {
        "code": "0000", 
        "msg": "处理成功"
    }, 
    "resp": {
        "pageNo": 1, 
        "totalPages": 1, 
        "totalCount": 11, 
        "gameId": 4077, 
        "issueNo": "20000", 
        "spmapers": {
            "平": "spf_1", 
            "让球平": "rqspf_1", 
            "让球胜": "rqspf_3", 
            "胜": "spf_3", 
            "负": "spf_0", 
            "让球负": "rqspf_0"
        }, 
        "leaguematches": [
            "欧罗巴杯"
        ], 
        "list": [
            {
                "matchNo": "001", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "巴特", 
                "guestTeam": "阿森纳", 
                "betId": "1649258", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 01:55", 
                "publishTime": "190214", 
                "concede": "1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "4.40", 
                    "spf_0": "1.24", 
                    "spf_3": "8.00", 
                    "rqspf_0": "1.90", 
                    "rqspf_3": "3.00", 
                    "rqspf_1": "3.35"
                }, 
                "isMiddle": 0, 
                "op": "7.88^4.86^1.39", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_2435.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_19.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "002", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "克拉斯诺", 
                "guestTeam": "勒沃库森", 
                "betId": "1649266", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 01:55", 
                "publishTime": "190214", 
                "concede": "1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "3.30", 
                    "spf_0": "1.82", 
                    "spf_3": "3.26", 
                    "rqspf_0": "3.50", 
                    "rqspf_3": "1.67", 
                    "rqspf_1": "3.65"
                }, 
                "isMiddle": 0, 
                "op": "3.52^3.60^2.02", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_10112.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_165.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "003", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "雷恩", 
                "guestTeam": "贝蒂斯", 
                "betId": "1649263", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 01:55", 
                "publishTime": "190214", 
                "concede": "1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4076,4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "2.85", 
                    "spf_0": "2.48", 
                    "spf_3": "2.48", 
                    "rqspf_0": "5.85", 
                    "rqspf_3": "1.35", 
                    "rqspf_1": "4.05"
                }, 
                "isMiddle": 0, 
                "op": "2.62^3.15^2.80", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_251.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_96.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "004", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "加拉塔萨", 
                "guestTeam": "本菲卡", 
                "betId": "1649271", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 01:55", 
                "publishTime": "190214", 
                "concede": "1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "2.90", 
                    "spf_0": "2.46", 
                    "spf_3": "2.46", 
                    "rqspf_0": "5.65", 
                    "rqspf_3": "1.36", 
                    "rqspf_1": "4.05"
                }, 
                "isMiddle": 0, 
                "op": "2.64^3.22^2.73", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_516.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_463.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "005", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "奥林匹亚", 
                "guestTeam": "迪纳摩", 
                "betId": "1649262", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 01:55", 
                "publishTime": "190214", 
                "concede": "-1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "3.00", 
                    "spf_0": "4.00", 
                    "spf_3": "1.74", 
                    "rqspf_0": "1.78", 
                    "rqspf_3": "3.40", 
                    "rqspf_1": "3.30"
                }, 
                "isMiddle": 0, 
                "op": "1.95^3.32^4.17", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": null, 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_712.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "006", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "布拉格斯", 
                "guestTeam": "亨克", 
                "betId": "1649285", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 01:55", 
                "publishTime": "190214", 
                "concede": "-1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "2.93", 
                    "spf_0": "2.75", 
                    "spf_3": "2.20", 
                    "rqspf_0": "1.44", 
                    "rqspf_3": "4.90", 
                    "rqspf_1": "3.85"
                }, 
                "isMiddle": 0, 
                "op": "2.43^3.24^2.98", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_651.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_147.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "007", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "布鲁日", 
                "guestTeam": "萨尔茨堡", 
                "betId": "1649264", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 04:00", 
                "publishTime": "190214", 
                "concede": "1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "3.20", 
                    "spf_0": "1.93", 
                    "spf_3": "3.05", 
                    "rqspf_0": "3.80", 
                    "rqspf_3": "1.60", 
                    "rqspf_1": "3.70"
                }, 
                "isMiddle": 0, 
                "op": "3.28^3.42^2.18", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_148.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_9.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "008", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "矿工", 
                "guestTeam": "法兰克福", 
                "betId": "1649269", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 04:00", 
                "publishTime": "190214", 
                "concede": "-1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "3.25", 
                    "spf_0": "2.75", 
                    "spf_3": "2.05", 
                    "rqspf_0": "1.54", 
                    "rqspf_3": "4.00", 
                    "rqspf_1": "3.85"
                }, 
                "isMiddle": 0, 
                "op": "2.27^3.37^3.15", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_716.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_423.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "009", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "比尔森", 
                "guestTeam": "萨格勒布", 
                "betId": "1649268", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 04:00", 
                "publishTime": "190214", 
                "concede": "-1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "3.00", 
                    "spf_0": "2.50", 
                    "spf_3": "2.35", 
                    "rqspf_0": "1.40", 
                    "rqspf_3": "5.30", 
                    "rqspf_1": "3.90"
                }, 
                "isMiddle": 0, 
                "op": "2.51^3.18^2.93", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_2534.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_653.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "010", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "苏黎世", 
                "guestTeam": "那不勒斯", 
                "betId": "1649261", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 04:00", 
                "publishTime": "190214", 
                "concede": "1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "4.15", 
                    "spf_0": "1.30", 
                    "spf_3": "6.75", 
                    "rqspf_0": "2.04", 
                    "rqspf_3": "2.70", 
                    "rqspf_1": "3.35"
                }, 
                "isMiddle": 0, 
                "op": "7.37^4.54^1.43", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_449.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_1419.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "011", 
                "matchName": "欧罗巴杯", 
                "homeTeam": "里斯本竞", 
                "guestTeam": "比利亚雷", 
                "betId": "1649267", 
                "endTime": "2019-02-14 23:50", 
                "matchTime": "2019-02-15 04:00", 
                "publishTime": "190214", 
                "concede": "-1", 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "spf_1": "3.00", 
                    "spf_0": "2.78", 
                    "spf_3": "2.15", 
                    "rqspf_0": "1.48", 
                    "rqspf_3": "4.55", 
                    "rqspf_1": "3.80"
                }, 
                "isMiddle": 0, 
                "op": "2.22^3.35^3.27", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_466.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_107.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }
        ], 
        "leaMatchCount": {
            "欧罗巴杯": 11, 
            "欧罗巴杯_0": 11
        }, 
        "publistNumMap": {
            "190214": 11, 
            "190214_2": 0
        }
    }
}