export const FOOTBALL4 ={
    "ro": {
        "code": "0000", 
        "msg": "处理成功"
    }, 
    "resp": {
        "pageNo": 1, 
        "totalPages": 1, 
        "totalCount": 10, 
        "gameId": 4072, 
        "issueNo": "20000", 
        "spmapers": {
            "0": "0", 
            "1": "1", 
            "2": "2", 
            "3": "3", 
            "4": "4", 
            "5": "5", 
            "6": "6", 
            "7+": "7"
        }, 
        "leaguematches": [
            "法甲", 
            "英冠", 
            "欧冠杯"
        ], 
        "list": [
            {
                "matchNo": "001", 
                "matchName": "法甲", 
                "homeTeam": "卡昂", 
                "guestTeam": "南特", 
                "betId": "1549893", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 02:30", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "6.50", 
                    "1": "3.20", 
                    "2": "3.00", 
                    "3": "4.00", 
                    "4": "7.50", 
                    "5": "15.00", 
                    "6": "28.00", 
                    "7": "36.00"
                }, 
                "isMiddle": 0, 
                "op": "3.44^3.09^2.28", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_257.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_263.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "002", 
                "matchName": "英冠", 
                "homeTeam": "伊普斯", 
                "guestTeam": "德比郡", 
                "betId": "1557792", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 03:45", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "8.50", 
                    "1": "3.80", 
                    "2": "3.10", 
                    "3": "3.65", 
                    "4": "6.00", 
                    "5": "11.00", 
                    "6": "21.00", 
                    "7": "33.00"
                }, 
                "isMiddle": 0, 
                "op": "4.30^3.43^1.84", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_68.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_47.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "003", 
                "matchName": "英冠", 
                "homeTeam": "普雷斯顿", 
                "guestTeam": "诺维奇", 
                "betId": "1557793", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 03:45", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "12.00", 
                    "1": "4.70", 
                    "2": "3.25", 
                    "3": "3.40", 
                    "4": "5.00", 
                    "5": "8.70", 
                    "6": "16.00", 
                    "7": "26.00"
                }, 
                "isMiddle": 0, 
                "op": "2.64^3.32^2.60", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_55.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_34.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "004", 
                "matchName": "英冠", 
                "homeTeam": "布伦特", 
                "guestTeam": "维拉", 
                "betId": "1557795", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 03:45", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "15.00", 
                    "1": "5.50", 
                    "2": "3.65", 
                    "3": "3.35", 
                    "4": "4.60", 
                    "5": "7.50", 
                    "6": "12.00", 
                    "7": "17.00"
                }, 
                "isMiddle": 0, 
                "op": "2.08^3.57^3.26", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_365.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_20.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "005", 
                "matchName": "英冠", 
                "homeTeam": "利兹联", 
                "guestTeam": "斯旺西", 
                "betId": "1557797", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 03:45", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "12.00", 
                    "1": "4.70", 
                    "2": "3.45", 
                    "3": "3.40", 
                    "4": "4.90", 
                    "5": "8.50", 
                    "6": "15.00", 
                    "7": "22.00"
                }, 
                "isMiddle": 0, 
                "op": "1.67^3.79^4.89", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_56.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_1194.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "006", 
                "matchName": "英冠", 
                "homeTeam": "谢菲联", 
                "guestTeam": "米德尔斯", 
                "betId": "1557799", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 03:45", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "7.50", 
                    "1": "3.65", 
                    "2": "3.05", 
                    "3": "3.75", 
                    "4": "6.50", 
                    "5": "12.00", 
                    "6": "24.00", 
                    "7": "33.00"
                }, 
                "isMiddle": 0, 
                "op": "1.98^3.25^3.92", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_51.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_17.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "007", 
                "matchName": "英冠", 
                "homeTeam": "维冈竞技", 
                "guestTeam": "斯托克城", 
                "betId": "1557800", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 03:45", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "8.00", 
                    "1": "3.85", 
                    "2": "3.10", 
                    "3": "3.65", 
                    "4": "6.00", 
                    "5": "11.00", 
                    "6": "22.00", 
                    "7": "33.00"
                }, 
                "isMiddle": 0, 
                "op": "2.71^3.12^2.65", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_61.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_58.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "008", 
                "matchName": "欧冠杯", 
                "homeTeam": "阿贾克斯", 
                "guestTeam": "皇马", 
                "betId": "1649254", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 04:00", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "17.00", 
                    "1": "7.00", 
                    "2": "3.85", 
                    "3": "3.55", 
                    "4": "4.10", 
                    "5": "6.50", 
                    "6": "10.50", 
                    "7": "13.00"
                }, 
                "isMiddle": 0, 
                "op": "3.70^3.89^1.93", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_253.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_82.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "009", 
                "matchName": "欧冠杯", 
                "homeTeam": "热刺", 
                "guestTeam": "多特蒙德", 
                "betId": "1649253", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 04:00", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4076,4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "12.00", 
                    "1": "5.10", 
                    "2": "3.25", 
                    "3": "3.55", 
                    "4": "4.50", 
                    "5": "9.00", 
                    "6": "15.00", 
                    "7": "22.00"
                }, 
                "isMiddle": 0, 
                "op": "2.15^3.51^3.40", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_33.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_99.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }, 
            {
                "matchNo": "010", 
                "matchName": "英冠", 
                "homeTeam": "雷丁", 
                "guestTeam": "布莱克本", 
                "betId": "1557801", 
                "endTime": "2019-02-13 23:50", 
                "matchTime": "2019-02-14 04:00", 
                "publishTime": "190213", 
                "concede": null, 
                "betplaytype": "4076,4071,4073,4072,4074", 
                "betSinglePlaytype": "4073,4072,4074", 
                "isHot": 0, 
                "spMap": {
                    "0": "9.50", 
                    "1": "4.15", 
                    "2": "3.20", 
                    "3": "3.50", 
                    "4": "5.60", 
                    "5": "10.00", 
                    "6": "18.00", 
                    "7": "29.00"
                }, 
                "isMiddle": 0, 
                "op": "2.66^3.16^2.66", 
                "homeRank": "", 
                "guestRank": "", 
                "homeImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_66.png", 
                "guestImgPath": "http://l.aicaicdn.com//images/pages/leaguelib/team_logo/tm_logo_21.png", 
                "betRatio": null, 
                "rfBetRatio": null
            }
        ], 
        "leaMatchCount": {
            "法甲": 1, 
            "欧冠杯_0": 2, 
            "英冠_0": 7, 
            "欧冠杯": 2, 
            "法甲_0": 1, 
            "英冠": 7
        }, 
        "publistNumMap": {
            "190213": 10, 
            "190213_2": 0
        }
    }
}